dist: xenial
language: node_js
cache: npm

branches:
  only:
    - master

before_install:
  - mkdir $TRAVIS_BUILD_DIR/bin && cd $TRAVIS_BUILD_DIR/bin
  - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_extended_0.53_Linux-64bit.tar.gz
  - tar -xvzf hugo_extended_0.53_Linux-64bit.tar.gz
  - cd $TRAVIS_BUILD_DIR

install:
  - npm install

script:
  - bin/hugo
  - bash scripts/ci/build-site-search-index.sh
  - bash scripts/ci/build-blog-search-index.sh
  - cp public/blog/atom.xml public/atom.xml
  - mkdir public/feed/ && cp public/blog/rss.xml public/feed/index.xml

after_success:
  - bash scripts/ci/deploy.sh
